name: Generate and publish KML files

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Echo test
        run: echo ${{ vars.LAMBDA_INVOKE_URL }}
      - name: Trigger AWS Lambda
        if: vars.LAMBDA_INVOKE_URL
        run: curl ${{ vars.LAMBDA_INVOKE_URL }}
