name: Generate and publish KML files

env:
  LAMBDA_INVOKE_URL:

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger AWS Lambda
        run: curl $LAMBDA_INVOKE_URL
